# Mosquitto Configuration
listener 11883
allow_anonymous true
persistence true
persistence_location /tmp/mosquitto/

# TLS Configuration
listener 18883
allow_anonymous true
cafile /home/saniyachavani/Documents/Precision_Pulse/dspl-precision-pulse-desktop/config/ca.crt
certfile /home/saniyachavani/Documents/Precision_Pulse/dspl-precision-pulse-desktop/config/server.crt
keyfile /home/saniyachavani/Documents/Precision_Pulse/dspl-precision-pulse-desktop/config/server.key
require_certificate false
tls_version tlsv1.2
